### ISSUE TITLE
Make fields as "variable selector" and not dropdown

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/outbrain-tag#2]
Would it be possible to make the "Order ID" and "Order Value" fields as "variable selector" and not "dropdown"?

It is easier to visualize all the variables in the "variable selector" text type of field.

![outbrain](https://github.com/stape-io/outbrain-tag/assets/6924386/25b90b6e-795b-4e6a-a5d1-e543171fb3b6)

**Comment by Bukashk0zzz** [comment]
Thanks but we do not plan to do this.
